Ftp ui hw4
psolikov/JavaSpring pull request #7
Opened 2018-05-13 00:02 UTC by psolikov

2018-05-30 07:34 UTC, jzuken commented
а чего тесты на тревисе не проходят?

2018-05-30 07:34 UTC, jzuken commented
сюда бы замерджить фиксы из прошлой задачи ещё

2018-05-30 07:39 UTC, jzuken requested changes

2018-05-30 07:39 UTC, jzuken commented on FTP/src/main/java/ru/spbau/solikov/ftp/UIFTP.java
> +        client = new FTPClient(Integer.parseInt(parameters.get(0)), parameters.get(1));
и тут те же ошибки
-1

2018-05-30 07:39 UTC, jzuken commented on FTP/src/main/java/ru/spbau/solikov/ftp/UIFTP.java
> +    private void setButtonsDownload(Collection<Button> buttons) {
сделайте, пожалуйста, чтобы содержимое каталогов отражалось всё же в таблице, как везде, а не отдельными кнопками

2018-06-22 09:36 UTC, jzuken requested changes

2018-06-22 09:36 UTC, jzuken commented on FTP/src/main/java/ru/spbau/solikov/ftp/UIFTP.java
> +                client = new FTPClient(Integer.parseInt(address.getText()),
а FTPClient хочет аргументы в другом порядке -- сначала порт, а потом адрес.
-1

2018-06-22 09:36 UTC, jzuken commented
и тут конфликс с мастером

2018-06-22 17:43 UTC, psolikov commented on FTP/src/main/java/ru/spbau/solikov/ftp/UIFTP.java
> +                client = new FTPClient(Integer.parseInt(address.getText()),
Даже интересно почему это работало

2018-06-23 18:06 UTC, merged